"""
Synthetic property catalog for the Real Estate Property Concierge demo.

Not a real dataset — a compact, deterministic catalog with enough variety
(cities, price bands, bedrooms, features, buy/rent) that the evaluators produce
*varying* scores. IDs follow <CITY>-<NNN> so grounding checks are exact.
"""

# ---------------------------------------------------------------- listings ---
LISTINGS = [
    # ---- Madrid ----
    {"id": "MAD-101", "city": "Madrid", "neighborhood": "Malasaña", "operation": "buy",
     "price": 389000, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1935,
     "energy_rating": "D", "floor": 3,
     "description": "Bright renovated 2-bed in the heart of Malasaña, 4 min walk to Tribunal metro."},
    {"id": "MAD-102", "city": "Madrid", "neighborhood": "Chamberí", "operation": "buy",
     "price": 465000, "bedrooms": 2, "bathrooms": 2, "size_m2": 85, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "air_conditioning"], "year_built": 1978,
     "energy_rating": "C", "floor": 5,
     "description": "Elegant 2-bed with private parking in leafy Chamberí, steps from Iglesia metro."},
    {"id": "MAD-103", "city": "Madrid", "neighborhood": "Lavapiés", "operation": "buy",
     "price": 279000, "bedrooms": 1, "bathrooms": 1, "size_m2": 55, "property_type": "apartment",
     "features": ["metro", "renovated"], "year_built": 1920, "energy_rating": "E", "floor": 2,
     "description": "Cosy 1-bed in vibrant, multicultural Lavapiés — great first purchase."},
    {"id": "MAD-104", "city": "Madrid", "neighborhood": "Salamanca", "operation": "buy",
     "price": 890000, "bedrooms": 3, "bathrooms": 2, "size_m2": 130, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "terrace", "air_conditioning", "renovated"],
     "year_built": 1965, "energy_rating": "B", "floor": 6,
     "description": "Prime 3-bed with terrace in exclusive Barrio de Salamanca."},
    {"id": "MAD-105", "city": "Madrid", "neighborhood": "Chamberí", "operation": "rent",
     "price": 1650, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished", "air_conditioning"], "year_built": 1980,
     "energy_rating": "D", "floor": 4,
     "description": "Furnished 2-bed to rent in Chamberí, ideal for professionals."},
    {"id": "MAD-106", "city": "Madrid", "neighborhood": "Tetuán", "operation": "rent",
     "price": 1150, "bedrooms": 2, "bathrooms": 1, "size_m2": 65, "property_type": "apartment",
     "features": ["metro", "elevator"], "year_built": 1972, "energy_rating": "E", "floor": 3,
     "description": "Affordable 2-bed rental in up-and-coming Tetuán, well connected."},

    # ---- Barcelona ----
    {"id": "BCN-201", "city": "Barcelona", "neighborhood": "Eixample", "operation": "buy",
     "price": 520000, "bedrooms": 2, "bathrooms": 2, "size_m2": 90, "property_type": "apartment",
     "features": ["metro", "elevator", "terrace", "air_conditioning"], "year_built": 1928,
     "energy_rating": "C", "floor": 4,
     "description": "Modernista 2-bed with terrace in the Eixample grid, near Passeig de Gràcia."},
    {"id": "BCN-202", "city": "Barcelona", "neighborhood": "Gràcia", "operation": "buy",
     "price": 398000, "bedrooms": 2, "bathrooms": 1, "size_m2": 68, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning"], "year_built": 1955,
     "energy_rating": "D", "floor": 2,
     "description": "Charming 2-bed in bohemian Gràcia, surrounded by plazas and cafés."},
    {"id": "BCN-203", "city": "Barcelona", "neighborhood": "Barceloneta", "operation": "buy",
     "price": 610000, "bedrooms": 3, "bathrooms": 2, "size_m2": 95, "property_type": "apartment",
     "features": ["metro", "elevator", "sea_view", "air_conditioning"], "year_built": 2001,
     "energy_rating": "B", "floor": 7,
     "description": "3-bed with sea views a block from Barceloneta beach."},
    {"id": "BCN-204", "city": "Barcelona", "neighborhood": "Poblenou", "operation": "rent",
     "price": 1900, "bedrooms": 3, "bathrooms": 2, "size_m2": 100, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "furnished", "air_conditioning"], "year_built": 2010,
     "energy_rating": "A", "floor": 5,
     "description": "Modern furnished 3-bed in tech-hub Poblenou, near 22@ district."},
    {"id": "BCN-205", "city": "Barcelona", "neighborhood": "Sants", "operation": "rent",
     "price": 1250, "bedrooms": 1, "bathrooms": 1, "size_m2": 50, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished"], "year_built": 1990, "energy_rating": "D", "floor": 3,
     "description": "Furnished 1-bed rental next to Sants station — unbeatable transport links."},

    # ---- Valencia ----
    {"id": "VLC-301", "city": "Valencia", "neighborhood": "Ruzafa", "operation": "buy",
     "price": 245000, "bedrooms": 2, "bathrooms": 1, "size_m2": 78, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning", "terrace"], "year_built": 1960,
     "energy_rating": "C", "floor": 4,
     "description": "Stylish 2-bed with balcony in trendy Ruzafa, Valencia's design district."},
    {"id": "VLC-302", "city": "Valencia", "neighborhood": "El Carmen", "operation": "buy",
     "price": 198000, "bedrooms": 1, "bathrooms": 1, "size_m2": 60, "property_type": "apartment",
     "features": ["renovated", "air_conditioning"], "year_built": 1900, "energy_rating": "E", "floor": 1,
     "description": "Historic 1-bed in the old town of El Carmen, full of character."},
    {"id": "VLC-303", "city": "Valencia", "neighborhood": "Cabañal", "operation": "buy",
     "price": 320000, "bedrooms": 3, "bathrooms": 2, "size_m2": 110, "property_type": "house",
     "features": ["sea_view", "terrace", "renovated", "garden"], "year_built": 1930,
     "energy_rating": "D", "floor": 0,
     "description": "Restored fisherman's house near the beach in the Cabañal quarter."},
    {"id": "VLC-304", "city": "Valencia", "neighborhood": "Ruzafa", "operation": "rent",
     "price": 1100, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "furnished", "air_conditioning"], "year_built": 1965,
     "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed to rent in the middle of Ruzafa's nightlife and markets."},

    # ---- Seville ----
    {"id": "SVQ-401", "city": "Seville", "neighborhood": "Triana", "operation": "buy",
     "price": 260000, "bedrooms": 2, "bathrooms": 1, "size_m2": 80, "property_type": "apartment",
     "features": ["renovated", "terrace", "air_conditioning"], "year_built": 1950,
     "energy_rating": "D", "floor": 2,
     "description": "Andalusian 2-bed with rooftop terrace in classic Triana."},
    {"id": "SVQ-402", "city": "Seville", "neighborhood": "Nervión", "operation": "buy",
     "price": 335000, "bedrooms": 3, "bathrooms": 2, "size_m2": 105, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "pool", "air_conditioning"], "year_built": 1995,
     "energy_rating": "C", "floor": 5,
     "description": "Family 3-bed with communal pool and parking in central Nervión."},
    {"id": "SVQ-403", "city": "Seville", "neighborhood": "Los Remedios", "operation": "rent",
     "price": 950, "bedrooms": 2, "bathrooms": 1, "size_m2": 75, "property_type": "apartment",
     "features": ["elevator", "air_conditioning", "furnished"], "year_built": 1985,
     "energy_rating": "D", "floor": 4,
     "description": "Comfortable furnished 2-bed rental in leafy Los Remedios."},

    # ---- Málaga ----
    {"id": "AGP-501", "city": "Málaga", "neighborhood": "Centro Histórico", "operation": "buy",
     "price": 355000, "bedrooms": 2, "bathrooms": 2, "size_m2": 82, "property_type": "apartment",
     "features": ["elevator", "renovated", "air_conditioning", "terrace"], "year_built": 1940,
     "energy_rating": "C", "floor": 3,
     "description": "Renovated 2-bed with terrace in Málaga's historic centre, near the cathedral."},
    {"id": "AGP-502", "city": "Málaga", "neighborhood": "El Palo", "operation": "buy",
     "price": 480000, "bedrooms": 3, "bathrooms": 2, "size_m2": 120, "property_type": "house",
     "features": ["sea_view", "terrace", "garden", "pool", "parking", "air_conditioning"],
     "year_built": 2005, "energy_rating": "B", "floor": 0,
     "description": "Beachside 3-bed house with pool and sea views in El Palo."},
    {"id": "AGP-503", "city": "Málaga", "neighborhood": "Teatinos", "operation": "rent",
     "price": 1050, "bedrooms": 2, "bathrooms": 2, "size_m2": 85, "property_type": "apartment",
     "features": ["elevator", "parking", "pool", "air_conditioning"], "year_built": 2012,
     "energy_rating": "A", "floor": 6,
     "description": "Bright modern 2-bed rental with pool in the university area of Teatinos."},

    # ---- Bilbao ----
    {"id": "BIO-601", "city": "Bilbao", "neighborhood": "Abando", "operation": "buy",
     "price": 410000, "bedrooms": 3, "bathrooms": 2, "size_m2": 100, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1970,
     "energy_rating": "C", "floor": 4,
     "description": "Spacious 3-bed in central Abando, walking distance to the Guggenheim."},
    {"id": "BIO-602", "city": "Bilbao", "neighborhood": "Indautxu", "operation": "rent",
     "price": 1300, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished", "air_conditioning"], "year_built": 1988,
     "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed rental in lively Indautxu, Bilbao's shopping district."},
]

# ------------------------------------------------------- neighborhood data ---
# Keyed by "City / Neighborhood". Used by the neighborhood_insights tool.
NEIGHBORHOODS = {
    "Madrid / Malasaña": {"avg_buy_eur_m2": 5400, "avg_rent_eur_m2": 22, "safety_score": 7,
        "transport": "Metro Tribunal & Bilbao (L1, L10); very walkable", "walk_score": 97,
        "schools": "Several bilingual primary schools within 1 km",
        "vibe": "Bohemian, nightlife-heavy, young creative crowd"},
    "Madrid / Chamberí": {"avg_buy_eur_m2": 5900, "avg_rent_eur_m2": 20, "safety_score": 9,
        "transport": "Metro Iglesia & Quevedo (L1, L2); excellent bus links", "walk_score": 95,
        "schools": "Strong public and private schools; near universities",
        "vibe": "Elegant, residential, family-friendly"},
    "Madrid / Lavapiés": {"avg_buy_eur_m2": 4300, "avg_rent_eur_m2": 19, "safety_score": 6,
        "transport": "Metro Lavapiés & Embajadores (L3, L5)", "walk_score": 96,
        "schools": "Public schools; strong community programs",
        "vibe": "Multicultural, artsy, lively street life"},
    "Madrid / Salamanca": {"avg_buy_eur_m2": 7200, "avg_rent_eur_m2": 24, "safety_score": 9,
        "transport": "Metro Serrano & Velázquez (L4)", "walk_score": 94,
        "schools": "Premium private and international schools",
        "vibe": "Upscale luxury shopping, embassies"},
    "Madrid / Tetuán": {"avg_buy_eur_m2": 4100, "avg_rent_eur_m2": 17, "safety_score": 7,
        "transport": "Metro Estrecho & Tetuán (L1)", "walk_score": 90,
        "schools": "Public schools; improving offer",
        "vibe": "Diverse, gentrifying, good value"},
    "Barcelona / Eixample": {"avg_buy_eur_m2": 5600, "avg_rent_eur_m2": 21, "safety_score": 8,
        "transport": "Metro Passeig de Gràcia (L2, L3, L4)", "walk_score": 96,
        "schools": "Wide range incl. international schools",
        "vibe": "Modernista architecture, central, upmarket"},
    "Barcelona / Gràcia": {"avg_buy_eur_m2": 5200, "avg_rent_eur_m2": 20, "safety_score": 8,
        "transport": "Metro Fontana & Joanic (L3, L4)", "walk_score": 95,
        "schools": "Good public schools; cooperatives",
        "vibe": "Village-like, bohemian, plaza culture"},
    "Barcelona / Barceloneta": {"avg_buy_eur_m2": 6100, "avg_rent_eur_m2": 23, "safety_score": 7,
        "transport": "Metro Barceloneta (L4)", "walk_score": 93,
        "schools": "Limited; better options nearby",
        "vibe": "Beachfront, touristy, seafood restaurants"},
    "Barcelona / Poblenou": {"avg_buy_eur_m2": 5300, "avg_rent_eur_m2": 22, "safety_score": 8,
        "transport": "Metro Poblenou & Llacuna (L4)", "walk_score": 92,
        "schools": "Modern schools; near 22@ tech district",
        "vibe": "Tech hub, rambla, beach access"},
    "Barcelona / Sants": {"avg_buy_eur_m2": 4600, "avg_rent_eur_m2": 19, "safety_score": 8,
        "transport": "Sants station (AVE, metro L1/L3/L5)", "walk_score": 94,
        "schools": "Solid public schools",
        "vibe": "Well-connected, local, good value"},
    "Valencia / Ruzafa": {"avg_buy_eur_m2": 3200, "avg_rent_eur_m2": 15, "safety_score": 8,
        "transport": "Metro Xàtiva nearby; bike-friendly", "walk_score": 95,
        "schools": "Good public and bilingual schools",
        "vibe": "Trendy, gastronomic, design-led"},
    "Valencia / El Carmen": {"avg_buy_eur_m2": 3000, "avg_rent_eur_m2": 14, "safety_score": 7,
        "transport": "Central; buses and bikes", "walk_score": 97,
        "schools": "Limited in old town",
        "vibe": "Historic, artistic, nightlife"},
    "Valencia / Cabañal": {"avg_buy_eur_m2": 2900, "avg_rent_eur_m2": 14, "safety_score": 7,
        "transport": "Tram to centre; near beach", "walk_score": 88,
        "schools": "Local public schools",
        "vibe": "Traditional seaside quarter, up-and-coming"},
    "Seville / Triana": {"avg_buy_eur_m2": 2700, "avg_rent_eur_m2": 12, "safety_score": 8,
        "transport": "Metro Plaza de Cuba (L1); buses", "walk_score": 94,
        "schools": "Good public schools",
        "vibe": "Flamenco heritage, riverside, authentic"},
    "Seville / Nervión": {"avg_buy_eur_m2": 2900, "avg_rent_eur_m2": 12, "safety_score": 9,
        "transport": "Metro Nervión (L1)", "walk_score": 90,
        "schools": "Strong schools; family area",
        "vibe": "Modern, commercial, residential"},
    "Seville / Los Remedios": {"avg_buy_eur_m2": 2800, "avg_rent_eur_m2": 12, "safety_score": 9,
        "transport": "Buses; near Triana bridge", "walk_score": 89,
        "schools": "Good private and public schools",
        "vibe": "Quiet, upper-middle-class, feria grounds"},
    "Málaga / Centro Histórico": {"avg_buy_eur_m2": 4300, "avg_rent_eur_m2": 16, "safety_score": 8,
        "transport": "Buses; walkable centre", "walk_score": 96,
        "schools": "Some central schools",
        "vibe": "Cultural, museums, pedestrian streets"},
    "Málaga / El Palo": {"avg_buy_eur_m2": 3800, "avg_rent_eur_m2": 15, "safety_score": 8,
        "transport": "Bus to centre; beachfront", "walk_score": 82,
        "schools": "Local schools",
        "vibe": "Relaxed beach neighbourhood, chiringuitos"},
    "Málaga / Teatinos": {"avg_buy_eur_m2": 3400, "avg_rent_eur_m2": 14, "safety_score": 8,
        "transport": "Metro Teatinos (L1, L2)", "walk_score": 84,
        "schools": "University area; modern schools",
        "vibe": "New-build, student and family mix"},
    "Bilbao / Abando": {"avg_buy_eur_m2": 4700, "avg_rent_eur_m2": 15, "safety_score": 9,
        "transport": "Metro Abando (L1, L2); central station", "walk_score": 95,
        "schools": "Good schools; central",
        "vibe": "Financial centre, near Guggenheim"},
    "Bilbao / Indautxu": {"avg_buy_eur_m2": 4900, "avg_rent_eur_m2": 15, "safety_score": 9,
        "transport": "Metro Indautxu (L1, L2)", "walk_score": 96,
        "schools": "Strong schools",
        "vibe": "Shopping, dining, lively squares"},
}

_BY_ID = {l["id"]: l for l in LISTINGS}


def get_listing(listing_id: str):
    return _BY_ID.get(listing_id)


def all_listing_ids():
    return list(_BY_ID.keys())


def neighborhood_key(city: str, neighborhood: str) -> str:
    return f"{city} / {neighborhood}"
