"""
Synthetic property catalog for the Real Estate Property Concierge demo.

Not a real dataset — a compact, deterministic catalog with enough variety
(cities across Europe, price bands, bedrooms, features, buy/rent) that the
evaluators produce *varying* scores. Coverage spans Spain (Madrid, Barcelona,
Valencia, Seville, Málaga, Bilbao) plus Lisbon, Paris, Berlin, Amsterdam, Rome,
Vienna, Dublin and Athens — all euro-priced so the mortgage/budget maths stay
consistent. IDs follow <CITY>-<NNN> (city = IATA-style code) so grounding checks
are exact.
"""

# ---------------------------------------------------------------- listings ---
LISTINGS = [
    # ---- Madrid ----
    {"id": "MAD-101", "city": "Madrid", "neighborhood": "Malasaña", "operation": "buy",
     "price": 389000, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1935,
     "energy_rating": "D", "floor": 3,
     "description": "Bright renovated 2-bed in the heart of Malasaña, 4 min walk to Tribunal metro."},
    {"id": "MAD-102", "city": "Madrid", "neighborhood": "Chamberí", "operation": "buy",
     "price": 465000, "bedrooms": 2, "bathrooms": 2, "size_m2": 85, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "air_conditioning"], "year_built": 1978,
     "energy_rating": "C", "floor": 5,
     "description": "Elegant 2-bed with private parking in leafy Chamberí, steps from Iglesia metro."},
    {"id": "MAD-103", "city": "Madrid", "neighborhood": "Lavapiés", "operation": "buy",
     "price": 279000, "bedrooms": 1, "bathrooms": 1, "size_m2": 55, "property_type": "apartment",
     "features": ["metro", "renovated"], "year_built": 1920, "energy_rating": "E", "floor": 2,
     "description": "Cosy 1-bed in vibrant, multicultural Lavapiés — great first purchase."},
    {"id": "MAD-104", "city": "Madrid", "neighborhood": "Salamanca", "operation": "buy",
     "price": 890000, "bedrooms": 3, "bathrooms": 2, "size_m2": 130, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "terrace", "air_conditioning", "renovated"],
     "year_built": 1965, "energy_rating": "B", "floor": 6,
     "description": "Prime 3-bed with terrace in exclusive Barrio de Salamanca."},
    {"id": "MAD-105", "city": "Madrid", "neighborhood": "Chamberí", "operation": "rent",
     "price": 1650, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished", "air_conditioning"], "year_built": 1980,
     "energy_rating": "D", "floor": 4,
     "description": "Furnished 2-bed to rent in Chamberí, ideal for professionals."},
    {"id": "MAD-106", "city": "Madrid", "neighborhood": "Tetuán", "operation": "rent",
     "price": 1150, "bedrooms": 2, "bathrooms": 1, "size_m2": 65, "property_type": "apartment",
     "features": ["metro", "elevator"], "year_built": 1972, "energy_rating": "E", "floor": 3,
     "description": "Affordable 2-bed rental in up-and-coming Tetuán, well connected."},

    # ---- Barcelona ----
    {"id": "BCN-201", "city": "Barcelona", "neighborhood": "Eixample", "operation": "buy",
     "price": 520000, "bedrooms": 2, "bathrooms": 2, "size_m2": 90, "property_type": "apartment",
     "features": ["metro", "elevator", "terrace", "air_conditioning"], "year_built": 1928,
     "energy_rating": "C", "floor": 4,
     "description": "Modernista 2-bed with terrace in the Eixample grid, near Passeig de Gràcia."},
    {"id": "BCN-202", "city": "Barcelona", "neighborhood": "Gràcia", "operation": "buy",
     "price": 398000, "bedrooms": 2, "bathrooms": 1, "size_m2": 68, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning"], "year_built": 1955,
     "energy_rating": "D", "floor": 2,
     "description": "Charming 2-bed in bohemian Gràcia, surrounded by plazas and cafés."},
    {"id": "BCN-203", "city": "Barcelona", "neighborhood": "Barceloneta", "operation": "buy",
     "price": 610000, "bedrooms": 3, "bathrooms": 2, "size_m2": 95, "property_type": "apartment",
     "features": ["metro", "elevator", "sea_view", "air_conditioning"], "year_built": 2001,
     "energy_rating": "B", "floor": 7,
     "description": "3-bed with sea views a block from Barceloneta beach."},
    {"id": "BCN-204", "city": "Barcelona", "neighborhood": "Poblenou", "operation": "rent",
     "price": 1900, "bedrooms": 3, "bathrooms": 2, "size_m2": 100, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "furnished", "air_conditioning"], "year_built": 2010,
     "energy_rating": "A", "floor": 5,
     "description": "Modern furnished 3-bed in tech-hub Poblenou, near 22@ district."},
    {"id": "BCN-205", "city": "Barcelona", "neighborhood": "Sants", "operation": "rent",
     "price": 1250, "bedrooms": 1, "bathrooms": 1, "size_m2": 50, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished"], "year_built": 1990, "energy_rating": "D", "floor": 3,
     "description": "Furnished 1-bed rental next to Sants station — unbeatable transport links."},

    # ---- Valencia ----
    {"id": "VLC-301", "city": "Valencia", "neighborhood": "Ruzafa", "operation": "buy",
     "price": 245000, "bedrooms": 2, "bathrooms": 1, "size_m2": 78, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning", "terrace"], "year_built": 1960,
     "energy_rating": "C", "floor": 4,
     "description": "Stylish 2-bed with balcony in trendy Ruzafa, Valencia's design district."},
    {"id": "VLC-302", "city": "Valencia", "neighborhood": "El Carmen", "operation": "buy",
     "price": 198000, "bedrooms": 1, "bathrooms": 1, "size_m2": 60, "property_type": "apartment",
     "features": ["renovated", "air_conditioning"], "year_built": 1900, "energy_rating": "E", "floor": 1,
     "description": "Historic 1-bed in the old town of El Carmen, full of character."},
    {"id": "VLC-303", "city": "Valencia", "neighborhood": "Cabañal", "operation": "buy",
     "price": 320000, "bedrooms": 3, "bathrooms": 2, "size_m2": 110, "property_type": "house",
     "features": ["sea_view", "terrace", "renovated", "garden"], "year_built": 1930,
     "energy_rating": "D", "floor": 0,
     "description": "Restored fisherman's house near the beach in the Cabañal quarter."},
    {"id": "VLC-304", "city": "Valencia", "neighborhood": "Ruzafa", "operation": "rent",
     "price": 1100, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "furnished", "air_conditioning"], "year_built": 1965,
     "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed to rent in the middle of Ruzafa's nightlife and markets."},

    # ---- Seville ----
    {"id": "SVQ-401", "city": "Seville", "neighborhood": "Triana", "operation": "buy",
     "price": 260000, "bedrooms": 2, "bathrooms": 1, "size_m2": 80, "property_type": "apartment",
     "features": ["renovated", "terrace", "air_conditioning"], "year_built": 1950,
     "energy_rating": "D", "floor": 2,
     "description": "Andalusian 2-bed with rooftop terrace in classic Triana."},
    {"id": "SVQ-402", "city": "Seville", "neighborhood": "Nervión", "operation": "buy",
     "price": 335000, "bedrooms": 3, "bathrooms": 2, "size_m2": 105, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "pool", "air_conditioning"], "year_built": 1995,
     "energy_rating": "C", "floor": 5,
     "description": "Family 3-bed with communal pool and parking in central Nervión."},
    {"id": "SVQ-403", "city": "Seville", "neighborhood": "Los Remedios", "operation": "rent",
     "price": 950, "bedrooms": 2, "bathrooms": 1, "size_m2": 75, "property_type": "apartment",
     "features": ["elevator", "air_conditioning", "furnished"], "year_built": 1985,
     "energy_rating": "D", "floor": 4,
     "description": "Comfortable furnished 2-bed rental in leafy Los Remedios."},

    # ---- Málaga ----
    {"id": "AGP-501", "city": "Málaga", "neighborhood": "Centro Histórico", "operation": "buy",
     "price": 355000, "bedrooms": 2, "bathrooms": 2, "size_m2": 82, "property_type": "apartment",
     "features": ["elevator", "renovated", "air_conditioning", "terrace"], "year_built": 1940,
     "energy_rating": "C", "floor": 3,
     "description": "Renovated 2-bed with terrace in Málaga's historic centre, near the cathedral."},
    {"id": "AGP-502", "city": "Málaga", "neighborhood": "El Palo", "operation": "buy",
     "price": 480000, "bedrooms": 3, "bathrooms": 2, "size_m2": 120, "property_type": "house",
     "features": ["sea_view", "terrace", "garden", "pool", "parking", "air_conditioning"],
     "year_built": 2005, "energy_rating": "B", "floor": 0,
     "description": "Beachside 3-bed house with pool and sea views in El Palo."},
    {"id": "AGP-503", "city": "Málaga", "neighborhood": "Teatinos", "operation": "rent",
     "price": 1050, "bedrooms": 2, "bathrooms": 2, "size_m2": 85, "property_type": "apartment",
     "features": ["elevator", "parking", "pool", "air_conditioning"], "year_built": 2012,
     "energy_rating": "A", "floor": 6,
     "description": "Bright modern 2-bed rental with pool in the university area of Teatinos."},

    # ---- Bilbao ----
    {"id": "BIO-601", "city": "Bilbao", "neighborhood": "Abando", "operation": "buy",
     "price": 410000, "bedrooms": 3, "bathrooms": 2, "size_m2": 100, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1970,
     "energy_rating": "C", "floor": 4,
     "description": "Spacious 3-bed in central Abando, walking distance to the Guggenheim."},
    {"id": "BIO-602", "city": "Bilbao", "neighborhood": "Indautxu", "operation": "rent",
     "price": 1300, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished", "air_conditioning"], "year_built": 1988,
     "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed rental in lively Indautxu, Bilbao's shopping district."},

    # ---- Lisbon (Portugal) ----
    {"id": "LIS-101", "city": "Lisbon", "neighborhood": "Alfama", "operation": "buy",
     "price": 445000, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["renovated", "terrace", "air_conditioning"], "year_built": 1925,
     "energy_rating": "D", "floor": 2,
     "description": "Renovated 2-bed with a tiled terrace in historic Alfama, Lisbon's oldest quarter."},
    {"id": "LIS-102", "city": "Lisbon", "neighborhood": "Chiado", "operation": "buy",
     "price": 620000, "bedrooms": 2, "bathrooms": 2, "size_m2": 82, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1955,
     "energy_rating": "C", "floor": 4,
     "description": "Elegant 2-bed in chic Chiado, steps from Baixa-Chiado metro and the opera."},
    {"id": "LIS-103", "city": "Lisbon", "neighborhood": "Príncipe Real", "operation": "buy",
     "price": 890000, "bedrooms": 3, "bathrooms": 2, "size_m2": 120, "property_type": "apartment",
     "features": ["elevator", "terrace", "renovated", "air_conditioning"], "year_built": 1900,
     "energy_rating": "C", "floor": 3,
     "description": "Restored 3-bed in fashionable Príncipe Real, gardens and boutiques at the door."},
    {"id": "LIS-104", "city": "Lisbon", "neighborhood": "Parque das Nações", "operation": "rent",
     "price": 1650, "bedrooms": 2, "bathrooms": 2, "size_m2": 88, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "furnished", "river_view", "air_conditioning"],
     "year_built": 2008, "energy_rating": "A", "floor": 7,
     "description": "Modern furnished 2-bed with Tagus river views in riverside Parque das Nações."},
    {"id": "LIS-105", "city": "Lisbon", "neighborhood": "Belém", "operation": "rent",
     "price": 1100, "bedrooms": 1, "bathrooms": 1, "size_m2": 52, "property_type": "apartment",
     "features": ["furnished", "renovated"], "year_built": 1990, "energy_rating": "D", "floor": 2,
     "description": "Bright furnished 1-bed in monumental Belém, near the river and the pastéis."},

    # ---- Paris (France) ----
    {"id": "PAR-101", "city": "Paris", "neighborhood": "Le Marais", "operation": "buy",
     "price": 830000, "bedrooms": 2, "bathrooms": 1, "size_m2": 58, "property_type": "apartment",
     "features": ["metro", "renovated"], "year_built": 1780, "energy_rating": "D", "floor": 3,
     "description": "Characterful 2-bed in the historic Marais, exposed beams, near Saint-Paul métro."},
    {"id": "PAR-102", "city": "Paris", "neighborhood": "Montmartre", "operation": "buy",
     "price": 540000, "bedrooms": 1, "bathrooms": 1, "size_m2": 42, "property_type": "apartment",
     "features": ["metro", "renovated"], "year_built": 1910, "energy_rating": "E", "floor": 5,
     "description": "Romantic 1-bed on the slopes of Montmartre, rooftop views toward Sacré-Cœur."},
    {"id": "PAR-103", "city": "Paris", "neighborhood": "Saint-Germain-des-Prés", "operation": "buy",
     "price": 1690000, "bedrooms": 3, "bathrooms": 2, "size_m2": 108, "property_type": "apartment",
     "features": ["metro", "elevator", "terrace", "renovated", "air_conditioning"], "year_built": 1870,
     "energy_rating": "C", "floor": 4,
     "description": "Prestigious 3-bed with a terrace in Saint-Germain-des-Prés, Left Bank elegance."},
    {"id": "PAR-104", "city": "Paris", "neighborhood": "Canal Saint-Martin", "operation": "rent",
     "price": 2400, "bedrooms": 2, "bathrooms": 1, "size_m2": 56, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished"], "year_built": 1930, "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed a canal-side stroll from Canal Saint-Martin's cafés and bars."},
    {"id": "PAR-105", "city": "Paris", "neighborhood": "Batignolles", "operation": "rent",
     "price": 1650, "bedrooms": 1, "bathrooms": 1, "size_m2": 38, "property_type": "apartment",
     "features": ["metro", "elevator", "furnished"], "year_built": 1995, "energy_rating": "C", "floor": 4,
     "description": "Cosy furnished 1-bed in leafy Batignolles, beside Martin Luther King park."},

    # ---- Berlin (Germany) ----
    {"id": "BER-101", "city": "Berlin", "neighborhood": "Mitte", "operation": "buy",
     "price": 560000, "bedrooms": 2, "bathrooms": 1, "size_m2": 78, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated"], "year_built": 1962, "energy_rating": "C", "floor": 3,
     "description": "Central 2-bed in Mitte, minutes from Museum Island and U-Bahn Rosenthaler Platz."},
    {"id": "BER-102", "city": "Berlin", "neighborhood": "Prenzlauer Berg", "operation": "buy",
     "price": 780000, "bedrooms": 3, "bathrooms": 2, "size_m2": 112, "property_type": "apartment",
     "features": ["elevator", "terrace", "renovated"], "year_built": 1905, "energy_rating": "C", "floor": 4,
     "description": "Spacious 3-bed Altbau with a balcony in family-friendly Prenzlauer Berg."},
    {"id": "BER-103", "city": "Berlin", "neighborhood": "Kreuzberg", "operation": "rent",
     "price": 1750, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "furnished"], "year_built": 1975, "energy_rating": "D", "floor": 2,
     "description": "Furnished 2-bed in creative, nightlife-rich Kreuzberg by Görlitzer Park."},
    {"id": "BER-104", "city": "Berlin", "neighborhood": "Charlottenburg", "operation": "buy",
     "price": 640000, "bedrooms": 2, "bathrooms": 2, "size_m2": 88, "property_type": "apartment",
     "features": ["metro", "elevator", "parking"], "year_built": 1988, "energy_rating": "C", "floor": 5,
     "description": "Well-kept 2-bed with parking in elegant Charlottenburg, near Kurfürstendamm."},
    {"id": "BER-105", "city": "Berlin", "neighborhood": "Friedrichshain", "operation": "rent",
     "price": 1150, "bedrooms": 1, "bathrooms": 1, "size_m2": 46, "property_type": "apartment",
     "features": ["metro", "furnished"], "year_built": 1998, "energy_rating": "D", "floor": 3,
     "description": "Affordable furnished 1-bed in buzzing Friedrichshain, close to the U5."},

    # ---- Amsterdam (Netherlands) ----
    {"id": "AMS-101", "city": "Amsterdam", "neighborhood": "Jordaan", "operation": "buy",
     "price": 695000, "bedrooms": 2, "bathrooms": 1, "size_m2": 74, "property_type": "apartment",
     "features": ["canal_view", "renovated"], "year_built": 1890, "energy_rating": "C", "floor": 2,
     "description": "Canal-view 2-bed in the picturesque Jordaan, gabled façade and bike-everywhere living."},
    {"id": "AMS-102", "city": "Amsterdam", "neighborhood": "De Pijp", "operation": "buy",
     "price": 610000, "bedrooms": 2, "bathrooms": 1, "size_m2": 68, "property_type": "apartment",
     "features": ["metro", "renovated"], "year_built": 1920, "energy_rating": "C", "floor": 3,
     "description": "Bright 2-bed in lively De Pijp, steps from the Albert Cuyp market."},
    {"id": "AMS-103", "city": "Amsterdam", "neighborhood": "Oud-Zuid", "operation": "buy",
     "price": 1150000, "bedrooms": 3, "bathrooms": 2, "size_m2": 122, "property_type": "apartment",
     "features": ["elevator", "garden", "renovated", "air_conditioning"], "year_built": 1930,
     "energy_rating": "B", "floor": 1,
     "description": "Refined 3-bed with a garden in prestigious Oud-Zuid, near the Vondelpark and museums."},
    {"id": "AMS-104", "city": "Amsterdam", "neighborhood": "Oost", "operation": "rent",
     "price": 2100, "bedrooms": 2, "bathrooms": 1, "size_m2": 76, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "furnished"], "year_built": 2012, "energy_rating": "A", "floor": 5,
     "description": "Modern furnished 2-bed with parking in up-and-coming Oost, near Amstel station."},
    {"id": "AMS-105", "city": "Amsterdam", "neighborhood": "Westerpark", "operation": "rent",
     "price": 1650, "bedrooms": 1, "bathrooms": 1, "size_m2": 48, "property_type": "apartment",
     "features": ["furnished", "renovated"], "year_built": 2005, "energy_rating": "B", "floor": 2,
     "description": "Stylish furnished 1-bed beside green Westerpark and the Westergas culture hub."},

    # ---- Rome (Italy) ----
    {"id": "ROM-101", "city": "Rome", "neighborhood": "Trastevere", "operation": "buy",
     "price": 520000, "bedrooms": 2, "bathrooms": 1, "size_m2": 80, "property_type": "apartment",
     "features": ["renovated", "terrace", "air_conditioning"], "year_built": 1930, "energy_rating": "D", "floor": 2,
     "description": "Charming 2-bed with a terrace in cobblestoned Trastevere, Rome's most romantic quarter."},
    {"id": "ROM-102", "city": "Rome", "neighborhood": "Monti", "operation": "buy",
     "price": 390000, "bedrooms": 1, "bathrooms": 1, "size_m2": 55, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning"], "year_built": 1920, "energy_rating": "E", "floor": 3,
     "description": "Boutique 1-bed in trendy Monti, a stroll from the Colosseum and Cavour metro."},
    {"id": "ROM-103", "city": "Rome", "neighborhood": "Prati", "operation": "buy",
     "price": 740000, "bedrooms": 3, "bathrooms": 2, "size_m2": 118, "property_type": "apartment",
     "features": ["metro", "elevator", "air_conditioning"], "year_built": 1960, "energy_rating": "C", "floor": 5,
     "description": "Elegant 3-bed in orderly Prati, near the Vatican and Lepanto metro."},
    {"id": "ROM-104", "city": "Rome", "neighborhood": "Testaccio", "operation": "rent",
     "price": 1550, "bedrooms": 2, "bathrooms": 1, "size_m2": 74, "property_type": "apartment",
     "features": ["metro", "furnished", "air_conditioning"], "year_built": 1980, "energy_rating": "D", "floor": 4,
     "description": "Furnished 2-bed in foodie Testaccio, the beating heart of Roman cuisine."},
    {"id": "ROM-105", "city": "Rome", "neighborhood": "Parioli", "operation": "rent",
     "price": 2600, "bedrooms": 3, "bathrooms": 2, "size_m2": 130, "property_type": "apartment",
     "features": ["elevator", "parking", "terrace", "furnished", "air_conditioning"], "year_built": 1995,
     "energy_rating": "C", "floor": 6,
     "description": "Spacious furnished 3-bed with terrace and parking in upscale, green Parioli."},

    # ---- Vienna (Austria) ----
    {"id": "VIE-101", "city": "Vienna", "neighborhood": "Innere Stadt", "operation": "buy",
     "price": 720000, "bedrooms": 2, "bathrooms": 2, "size_m2": 85, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated"], "year_built": 1900, "energy_rating": "C", "floor": 3,
     "description": "Refined 2-bed in the Innere Stadt, within the Ring and steps from Stephansplatz U-Bahn."},
    {"id": "VIE-102", "city": "Vienna", "neighborhood": "Leopoldstadt", "operation": "buy",
     "price": 520000, "bedrooms": 2, "bathrooms": 1, "size_m2": 78, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated"], "year_built": 1970, "energy_rating": "C", "floor": 4,
     "description": "Modern 2-bed in Leopoldstadt near the Prater park and Praterstern transport hub."},
    {"id": "VIE-103", "city": "Vienna", "neighborhood": "Neubau", "operation": "rent",
     "price": 1650, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["metro", "furnished"], "year_built": 1985, "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed in creative Neubau, home to the MuseumsQuartier and design shops."},
    {"id": "VIE-104", "city": "Vienna", "neighborhood": "Landstraße", "operation": "buy",
     "price": 680000, "bedrooms": 3, "bathrooms": 2, "size_m2": 110, "property_type": "apartment",
     "features": ["metro", "elevator", "parking", "terrace"], "year_built": 2004, "energy_rating": "B", "floor": 5,
     "description": "Bright 3-bed with terrace and parking in well-connected Landstraße, near Belvedere."},

    # ---- Dublin (Ireland) ----
    {"id": "DUB-101", "city": "Dublin", "neighborhood": "Ranelagh", "operation": "buy",
     "price": 625000, "bedrooms": 2, "bathrooms": 1, "size_m2": 76, "property_type": "apartment",
     "features": ["renovated", "parking"], "year_built": 1998, "energy_rating": "C", "floor": 2,
     "description": "Modern 2-bed with parking in leafy Ranelagh, a short Luas ride from the city centre."},
    {"id": "DUB-102", "city": "Dublin", "neighborhood": "Portobello", "operation": "buy",
     "price": 395000, "bedrooms": 1, "bathrooms": 1, "size_m2": 50, "property_type": "apartment",
     "features": ["renovated"], "year_built": 2001, "energy_rating": "C", "floor": 1,
     "description": "Bright 1-bed by the Grand Canal in vibrant Portobello, walkable to St Stephen's Green."},
    {"id": "DUB-103", "city": "Dublin", "neighborhood": "Grand Canal Dock", "operation": "rent",
     "price": 2650, "bedrooms": 2, "bathrooms": 2, "size_m2": 82, "property_type": "apartment",
     "features": ["elevator", "parking", "furnished"], "year_built": 2015, "energy_rating": "A", "floor": 6,
     "description": "Premium furnished 2-bed in Grand Canal Dock, Dublin's waterside tech quarter."},
    {"id": "DUB-104", "city": "Dublin", "neighborhood": "Stoneybatter", "operation": "buy",
     "price": 695000, "bedrooms": 3, "bathrooms": 2, "size_m2": 108, "property_type": "house",
     "features": ["garden", "renovated"], "year_built": 1935, "energy_rating": "D", "floor": 0,
     "description": "Restored 3-bed redbrick house with a garden in trendy, village-like Stoneybatter."},
    {"id": "DUB-105", "city": "Dublin", "neighborhood": "Rathmines", "operation": "rent",
     "price": 2200, "bedrooms": 2, "bathrooms": 1, "size_m2": 70, "property_type": "apartment",
     "features": ["furnished", "parking"], "year_built": 1990, "energy_rating": "D", "floor": 3,
     "description": "Furnished 2-bed in popular, student-friendly Rathmines with off-street parking."},

    # ---- Athens (Greece) ----
    {"id": "ATH-101", "city": "Athens", "neighborhood": "Koukaki", "operation": "buy",
     "price": 245000, "bedrooms": 2, "bathrooms": 1, "size_m2": 78, "property_type": "apartment",
     "features": ["metro", "renovated", "air_conditioning"], "year_built": 1975, "energy_rating": "D", "floor": 3,
     "description": "Renovated 2-bed in hip Koukaki below the Acropolis, near Syngrou-Fix metro."},
    {"id": "ATH-102", "city": "Athens", "neighborhood": "Kolonaki", "operation": "buy",
     "price": 560000, "bedrooms": 3, "bathrooms": 2, "size_m2": 120, "property_type": "apartment",
     "features": ["metro", "elevator", "renovated", "air_conditioning"], "year_built": 1985,
     "energy_rating": "C", "floor": 5,
     "description": "Upscale 3-bed in chic Kolonaki, designer boutiques and Evangelismos metro nearby."},
    {"id": "ATH-103", "city": "Athens", "neighborhood": "Plaka", "operation": "buy",
     "price": 280000, "bedrooms": 1, "bathrooms": 1, "size_m2": 55, "property_type": "apartment",
     "features": ["renovated", "air_conditioning"], "year_built": 1930, "energy_rating": "E", "floor": 2,
     "description": "Neoclassical 1-bed in the old town of Plaka, in the shadow of the Acropolis."},
    {"id": "ATH-104", "city": "Athens", "neighborhood": "Glyfada", "operation": "buy",
     "price": 620000, "bedrooms": 3, "bathrooms": 2, "size_m2": 135, "property_type": "house",
     "features": ["sea_view", "garden", "pool", "parking", "air_conditioning"], "year_built": 2003,
     "energy_rating": "B", "floor": 0,
     "description": "Coastal 3-bed house with pool and sea views in Glyfada on the Athens Riviera."},
    {"id": "ATH-105", "city": "Athens", "neighborhood": "Exarcheia", "operation": "rent",
     "price": 900, "bedrooms": 2, "bathrooms": 1, "size_m2": 72, "property_type": "apartment",
     "features": ["metro", "furnished"], "year_built": 1970, "energy_rating": "E", "floor": 4,
     "description": "Affordable furnished 2-bed in bohemian, political Exarcheia, near Omonia metro."},
]

# ------------------------------------------------------- neighborhood data ---
# Keyed by "City / Neighborhood". Used by the neighborhood_insights tool.
NEIGHBORHOODS = {
    "Madrid / Malasaña": {"avg_buy_eur_m2": 5400, "avg_rent_eur_m2": 22, "safety_score": 7,
        "transport": "Metro Tribunal & Bilbao (L1, L10); very walkable", "walk_score": 97,
        "schools": "Several bilingual primary schools within 1 km",
        "vibe": "Bohemian, nightlife-heavy, young creative crowd"},
    "Madrid / Chamberí": {"avg_buy_eur_m2": 5900, "avg_rent_eur_m2": 20, "safety_score": 9,
        "transport": "Metro Iglesia & Quevedo (L1, L2); excellent bus links", "walk_score": 95,
        "schools": "Strong public and private schools; near universities",
        "vibe": "Elegant, residential, family-friendly"},
    "Madrid / Lavapiés": {"avg_buy_eur_m2": 4300, "avg_rent_eur_m2": 19, "safety_score": 6,
        "transport": "Metro Lavapiés & Embajadores (L3, L5)", "walk_score": 96,
        "schools": "Public schools; strong community programs",
        "vibe": "Multicultural, artsy, lively street life"},
    "Madrid / Salamanca": {"avg_buy_eur_m2": 7200, "avg_rent_eur_m2": 24, "safety_score": 9,
        "transport": "Metro Serrano & Velázquez (L4)", "walk_score": 94,
        "schools": "Premium private and international schools",
        "vibe": "Upscale luxury shopping, embassies"},
    "Madrid / Tetuán": {"avg_buy_eur_m2": 4100, "avg_rent_eur_m2": 17, "safety_score": 7,
        "transport": "Metro Estrecho & Tetuán (L1)", "walk_score": 90,
        "schools": "Public schools; improving offer",
        "vibe": "Diverse, gentrifying, good value"},
    "Barcelona / Eixample": {"avg_buy_eur_m2": 5600, "avg_rent_eur_m2": 21, "safety_score": 8,
        "transport": "Metro Passeig de Gràcia (L2, L3, L4)", "walk_score": 96,
        "schools": "Wide range incl. international schools",
        "vibe": "Modernista architecture, central, upmarket"},
    "Barcelona / Gràcia": {"avg_buy_eur_m2": 5200, "avg_rent_eur_m2": 20, "safety_score": 8,
        "transport": "Metro Fontana & Joanic (L3, L4)", "walk_score": 95,
        "schools": "Good public schools; cooperatives",
        "vibe": "Village-like, bohemian, plaza culture"},
    "Barcelona / Barceloneta": {"avg_buy_eur_m2": 6100, "avg_rent_eur_m2": 23, "safety_score": 7,
        "transport": "Metro Barceloneta (L4)", "walk_score": 93,
        "schools": "Limited; better options nearby",
        "vibe": "Beachfront, touristy, seafood restaurants"},
    "Barcelona / Poblenou": {"avg_buy_eur_m2": 5300, "avg_rent_eur_m2": 22, "safety_score": 8,
        "transport": "Metro Poblenou & Llacuna (L4)", "walk_score": 92,
        "schools": "Modern schools; near 22@ tech district",
        "vibe": "Tech hub, rambla, beach access"},
    "Barcelona / Sants": {"avg_buy_eur_m2": 4600, "avg_rent_eur_m2": 19, "safety_score": 8,
        "transport": "Sants station (AVE, metro L1/L3/L5)", "walk_score": 94,
        "schools": "Solid public schools",
        "vibe": "Well-connected, local, good value"},
    "Valencia / Ruzafa": {"avg_buy_eur_m2": 3200, "avg_rent_eur_m2": 15, "safety_score": 8,
        "transport": "Metro Xàtiva nearby; bike-friendly", "walk_score": 95,
        "schools": "Good public and bilingual schools",
        "vibe": "Trendy, gastronomic, design-led"},
    "Valencia / El Carmen": {"avg_buy_eur_m2": 3000, "avg_rent_eur_m2": 14, "safety_score": 7,
        "transport": "Central; buses and bikes", "walk_score": 97,
        "schools": "Limited in old town",
        "vibe": "Historic, artistic, nightlife"},
    "Valencia / Cabañal": {"avg_buy_eur_m2": 2900, "avg_rent_eur_m2": 14, "safety_score": 7,
        "transport": "Tram to centre; near beach", "walk_score": 88,
        "schools": "Local public schools",
        "vibe": "Traditional seaside quarter, up-and-coming"},
    "Seville / Triana": {"avg_buy_eur_m2": 2700, "avg_rent_eur_m2": 12, "safety_score": 8,
        "transport": "Metro Plaza de Cuba (L1); buses", "walk_score": 94,
        "schools": "Good public schools",
        "vibe": "Flamenco heritage, riverside, authentic"},
    "Seville / Nervión": {"avg_buy_eur_m2": 2900, "avg_rent_eur_m2": 12, "safety_score": 9,
        "transport": "Metro Nervión (L1)", "walk_score": 90,
        "schools": "Strong schools; family area",
        "vibe": "Modern, commercial, residential"},
    "Seville / Los Remedios": {"avg_buy_eur_m2": 2800, "avg_rent_eur_m2": 12, "safety_score": 9,
        "transport": "Buses; near Triana bridge", "walk_score": 89,
        "schools": "Good private and public schools",
        "vibe": "Quiet, upper-middle-class, feria grounds"},
    "Málaga / Centro Histórico": {"avg_buy_eur_m2": 4300, "avg_rent_eur_m2": 16, "safety_score": 8,
        "transport": "Buses; walkable centre", "walk_score": 96,
        "schools": "Some central schools",
        "vibe": "Cultural, museums, pedestrian streets"},
    "Málaga / El Palo": {"avg_buy_eur_m2": 3800, "avg_rent_eur_m2": 15, "safety_score": 8,
        "transport": "Bus to centre; beachfront", "walk_score": 82,
        "schools": "Local schools",
        "vibe": "Relaxed beach neighbourhood, chiringuitos"},
    "Málaga / Teatinos": {"avg_buy_eur_m2": 3400, "avg_rent_eur_m2": 14, "safety_score": 8,
        "transport": "Metro Teatinos (L1, L2)", "walk_score": 84,
        "schools": "University area; modern schools",
        "vibe": "New-build, student and family mix"},
    "Bilbao / Abando": {"avg_buy_eur_m2": 4700, "avg_rent_eur_m2": 15, "safety_score": 9,
        "transport": "Metro Abando (L1, L2); central station", "walk_score": 95,
        "schools": "Good schools; central",
        "vibe": "Financial centre, near Guggenheim"},
    "Bilbao / Indautxu": {"avg_buy_eur_m2": 4900, "avg_rent_eur_m2": 15, "safety_score": 9,
        "transport": "Metro Indautxu (L1, L2)", "walk_score": 96,
        "schools": "Strong schools",
        "vibe": "Shopping, dining, lively squares"},

    # ---- Lisbon (Portugal) ----
    "Lisbon / Alfama": {"avg_buy_eur_m2": 5000, "avg_rent_eur_m2": 18, "safety_score": 7,
        "transport": "Tram 28 & buses; near Terreiro do Paço", "walk_score": 92,
        "schools": "Limited in the old town",
        "vibe": "Historic maze of alleys, Fado houses, viewpoints"},
    "Lisbon / Chiado": {"avg_buy_eur_m2": 6200, "avg_rent_eur_m2": 21, "safety_score": 8,
        "transport": "Metro Baixa-Chiado (Blue & Green)", "walk_score": 96,
        "schools": "Central; some private schools",
        "vibe": "Chic, cultural, theatres and shopping"},
    "Lisbon / Príncipe Real": {"avg_buy_eur_m2": 6800, "avg_rent_eur_m2": 22, "safety_score": 8,
        "transport": "Buses; near Rato metro", "walk_score": 94,
        "schools": "Good private schools nearby",
        "vibe": "Fashionable, gardens, design boutiques"},
    "Lisbon / Parque das Nações": {"avg_buy_eur_m2": 4800, "avg_rent_eur_m2": 17, "safety_score": 9,
        "transport": "Metro Oriente (Red); Oriente station", "walk_score": 88,
        "schools": "Modern international schools",
        "vibe": "Riverside, modern, family-friendly"},
    "Lisbon / Belém": {"avg_buy_eur_m2": 4600, "avg_rent_eur_m2": 16, "safety_score": 8,
        "transport": "Tram 15 & trains to Cais do Sodré", "walk_score": 85,
        "schools": "Local schools",
        "vibe": "Monumental, riverside, museums"},

    # ---- Paris (France) ----
    "Paris / Le Marais": {"avg_buy_eur_m2": 13500, "avg_rent_eur_m2": 38, "safety_score": 8,
        "transport": "Métro Saint-Paul & Rambuteau (L1, L11)", "walk_score": 98,
        "schools": "Central bilingual options",
        "vibe": "Historic, arty, boutiques and galleries"},
    "Paris / Montmartre": {"avg_buy_eur_m2": 11000, "avg_rent_eur_m2": 34, "safety_score": 7,
        "transport": "Métro Abbesses & Anvers (L12, L2)", "walk_score": 95,
        "schools": "Local public schools",
        "vibe": "Bohemian hilltop, artists, Sacré-Cœur"},
    "Paris / Saint-Germain-des-Prés": {"avg_buy_eur_m2": 15500, "avg_rent_eur_m2": 42, "safety_score": 9,
        "transport": "Métro Saint-Germain-des-Prés (L4)", "walk_score": 97,
        "schools": "Prestigious lycées nearby",
        "vibe": "Left Bank literary elegance, cafés"},
    "Paris / Canal Saint-Martin": {"avg_buy_eur_m2": 11500, "avg_rent_eur_m2": 35, "safety_score": 7,
        "transport": "Métro République & Jacques Bonsergent (L5, L8)", "walk_score": 96,
        "schools": "Public schools",
        "vibe": "Trendy, canal-side, young and lively"},
    "Paris / Batignolles": {"avg_buy_eur_m2": 10500, "avg_rent_eur_m2": 33, "safety_score": 8,
        "transport": "Métro Rome & Place de Clichy (L2, L13)", "walk_score": 93,
        "schools": "Good public schools; family area",
        "vibe": "Village-like, green, gentrified"},

    # ---- Berlin (Germany) ----
    "Berlin / Mitte": {"avg_buy_eur_m2": 6500, "avg_rent_eur_m2": 20, "safety_score": 8,
        "transport": "U-Bahn & S-Bahn hub; Alexanderplatz", "walk_score": 96,
        "schools": "International schools nearby",
        "vibe": "Central, historic, galleries and government"},
    "Berlin / Prenzlauer Berg": {"avg_buy_eur_m2": 6200, "avg_rent_eur_m2": 19, "safety_score": 9,
        "transport": "U2 Eberswalder Str.; trams", "walk_score": 95,
        "schools": "Excellent; very much a family area",
        "vibe": "Leafy Altbau streets, cafés, young families"},
    "Berlin / Kreuzberg": {"avg_buy_eur_m2": 5600, "avg_rent_eur_m2": 18, "safety_score": 7,
        "transport": "U1/U8 Kottbusser Tor", "walk_score": 94,
        "schools": "Public schools; mixed offer",
        "vibe": "Multicultural, nightlife, street art"},
    "Berlin / Charlottenburg": {"avg_buy_eur_m2": 6000, "avg_rent_eur_m2": 18, "safety_score": 9,
        "transport": "U7 & S-Bahn; near Zoologischer Garten", "walk_score": 92,
        "schools": "Strong public and private schools",
        "vibe": "Elegant, established West Berlin, shopping"},
    "Berlin / Friedrichshain": {"avg_buy_eur_m2": 5400, "avg_rent_eur_m2": 18, "safety_score": 8,
        "transport": "U5 Frankfurter Tor; trams", "walk_score": 93,
        "schools": "Public schools",
        "vibe": "Youthful, clubs, riverside East Side Gallery"},

    # ---- Amsterdam (Netherlands) ----
    "Amsterdam / Jordaan": {"avg_buy_eur_m2": 9000, "avg_rent_eur_m2": 28, "safety_score": 9,
        "transport": "Trams; near Amsterdam Centraal", "walk_score": 97,
        "schools": "Central primary schools",
        "vibe": "Picturesque canals, galleries, boutiques"},
    "Amsterdam / De Pijp": {"avg_buy_eur_m2": 8200, "avg_rent_eur_m2": 26, "safety_score": 8,
        "transport": "Metro 52 De Pijp; trams", "walk_score": 96,
        "schools": "Good public schools",
        "vibe": "Lively, multicultural, Albert Cuyp market"},
    "Amsterdam / Oud-Zuid": {"avg_buy_eur_m2": 9500, "avg_rent_eur_m2": 30, "safety_score": 9,
        "transport": "Trams; near the museum quarter", "walk_score": 94,
        "schools": "Top schools incl. international",
        "vibe": "Upmarket, museums, Vondelpark"},
    "Amsterdam / Oost": {"avg_buy_eur_m2": 7000, "avg_rent_eur_m2": 24, "safety_score": 8,
        "transport": "Metro 51/53/54; Amstel station", "walk_score": 92,
        "schools": "Modern schools",
        "vibe": "Diverse, up-and-coming, green"},
    "Amsterdam / Westerpark": {"avg_buy_eur_m2": 7500, "avg_rent_eur_m2": 25, "safety_score": 8,
        "transport": "Trams & buses; near Sloterdijk", "walk_score": 93,
        "schools": "Good schools",
        "vibe": "Creative, park life, Westergas events"},

    # ---- Rome (Italy) ----
    "Rome / Trastevere": {"avg_buy_eur_m2": 5500, "avg_rent_eur_m2": 19, "safety_score": 7,
        "transport": "Trams & buses; Trastevere station", "walk_score": 95,
        "schools": "Limited; better across the river",
        "vibe": "Cobbled, romantic, trattorias and nightlife"},
    "Rome / Monti": {"avg_buy_eur_m2": 5200, "avg_rent_eur_m2": 18, "safety_score": 8,
        "transport": "Metro Cavour (Line B)", "walk_score": 96,
        "schools": "Central schools",
        "vibe": "Trendy, artisan shops, near the Forum"},
    "Rome / Prati": {"avg_buy_eur_m2": 5000, "avg_rent_eur_m2": 17, "safety_score": 9,
        "transport": "Metro Lepanto & Ottaviano (Line A)", "walk_score": 94,
        "schools": "Good schools; residential",
        "vibe": "Elegant, orderly, shopping near the Vatican"},
    "Rome / Testaccio": {"avg_buy_eur_m2": 4400, "avg_rent_eur_m2": 16, "safety_score": 8,
        "transport": "Metro Piramide (Line B)", "walk_score": 93,
        "schools": "Local schools",
        "vibe": "Authentic, foodie, market and clubs"},
    "Rome / Parioli": {"avg_buy_eur_m2": 5800, "avg_rent_eur_m2": 20, "safety_score": 9,
        "transport": "Metro & trams; near Villa Borghese", "walk_score": 88,
        "schools": "Premium private schools",
        "vibe": "Affluent, green, embassies"},

    # ---- Vienna (Austria) ----
    "Vienna / Innere Stadt": {"avg_buy_eur_m2": 9500, "avg_rent_eur_m2": 24, "safety_score": 9,
        "transport": "U1/U3 Stephansplatz", "walk_score": 97,
        "schools": "Central; international options",
        "vibe": "Imperial, opera, luxury shopping"},
    "Vienna / Leopoldstadt": {"avg_buy_eur_m2": 6200, "avg_rent_eur_m2": 18, "safety_score": 8,
        "transport": "U1/U2 Praterstern", "walk_score": 93,
        "schools": "Good public schools",
        "vibe": "Diverse, Prater park, riverside"},
    "Vienna / Neubau": {"avg_buy_eur_m2": 7000, "avg_rent_eur_m2": 20, "safety_score": 8,
        "transport": "U3 Neubaugasse; trams", "walk_score": 96,
        "schools": "Central schools",
        "vibe": "Creative, MuseumsQuartier, boutiques"},
    "Vienna / Landstraße": {"avg_buy_eur_m2": 6500, "avg_rent_eur_m2": 18, "safety_score": 9,
        "transport": "U3/U4; near Wien Mitte", "walk_score": 92,
        "schools": "Strong schools",
        "vibe": "Central-east, Belvedere, well-connected"},

    # ---- Dublin (Ireland) ----
    "Dublin / Ranelagh": {"avg_buy_eur_m2": 8000, "avg_rent_eur_m2": 30, "safety_score": 9,
        "transport": "Luas Green Line to the city centre", "walk_score": 93,
        "schools": "Excellent schools; family area",
        "vibe": "Leafy, gastropubs, professional"},
    "Dublin / Portobello": {"avg_buy_eur_m2": 8200, "avg_rent_eur_m2": 32, "safety_score": 8,
        "transport": "Buses; walkable; near the Luas", "walk_score": 96,
        "schools": "Central schools",
        "vibe": "Canal-side, bohemian, cafés"},
    "Dublin / Grand Canal Dock": {"avg_buy_eur_m2": 8500, "avg_rent_eur_m2": 34, "safety_score": 8,
        "transport": "DART & Luas; docklands", "walk_score": 92,
        "schools": "Modern schools nearby",
        "vibe": "Waterside tech quarter, modern towers"},
    "Dublin / Stoneybatter": {"avg_buy_eur_m2": 7500, "avg_rent_eur_m2": 28, "safety_score": 8,
        "transport": "Buses & Luas Red Line", "walk_score": 94,
        "schools": "Local schools",
        "vibe": "Village feel, hip, redbrick terraces"},
    "Dublin / Rathmines": {"avg_buy_eur_m2": 7800, "avg_rent_eur_m2": 30, "safety_score": 8,
        "transport": "Buses; near the Luas", "walk_score": 95,
        "schools": "Many schools; student area",
        "vibe": "Lively, red-brick, student and family mix"},

    # ---- Athens (Greece) ----
    "Athens / Koukaki": {"avg_buy_eur_m2": 3200, "avg_rent_eur_m2": 13, "safety_score": 8,
        "transport": "Metro Syngrou-Fix (Line 2)", "walk_score": 95,
        "schools": "Local schools",
        "vibe": "Hip, under the Acropolis, cafés"},
    "Athens / Kolonaki": {"avg_buy_eur_m2": 4200, "avg_rent_eur_m2": 16, "safety_score": 9,
        "transport": "Metro Evangelismos (Line 3)", "walk_score": 94,
        "schools": "Private & international schools",
        "vibe": "Upscale, designer shopping, galleries"},
    "Athens / Plaka": {"avg_buy_eur_m2": 3800, "avg_rent_eur_m2": 15, "safety_score": 8,
        "transport": "Metro Akropoli & Monastiraki", "walk_score": 97,
        "schools": "Limited in the old town",
        "vibe": "Neoclassical old town, tourist heart"},
    "Athens / Glyfada": {"avg_buy_eur_m2": 3600, "avg_rent_eur_m2": 15, "safety_score": 9,
        "transport": "Tram to the centre; coastal road", "walk_score": 82,
        "schools": "Good private schools",
        "vibe": "Athens Riviera, beach clubs, marinas"},
    "Athens / Exarcheia": {"avg_buy_eur_m2": 2600, "avg_rent_eur_m2": 12, "safety_score": 6,
        "transport": "Metro Omonia & Panepistimio", "walk_score": 94,
        "schools": "Public schools",
        "vibe": "Bohemian, political, street art and bars"},
}

_BY_ID = {l["id"]: l for l in LISTINGS}


def get_listing(listing_id: str):
    return _BY_ID.get(listing_id)


def all_listing_ids():
    return list(_BY_ID.keys())


def neighborhood_key(city: str, neighborhood: str) -> str:
    return f"{city} / {neighborhood}"
